name: Network Deploy

on:
  workflow_dispatch:
    inputs:
      spec:
        description: "Path to the Digger config file."
        required: false
        type: string
      run_name:
        description: "Optional name for the run."
        required: false
        type: string

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  terraform:
    uses: Platly/github-actions/.github/workflows/workflow_terraform_run.yml@build/setup-digger
    with:
      AWS_REGION: eu-central-1
    secrets:
      AWS_IAM_ROLE: ${{ secrets.AWS_NETWORK_IAM_ROLE }}