name: Network Deploy

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  terraform:
    uses: Platly/github-actions/.github/workflows/workflow_terraform_run.yml@main
    with:
      AWS_REGION: eu-central-1
    secrets:
      AWS_IAM_ROLE: ${{ secrets.AWS_NETWORK_IAM_ROLE }}